Hanoi.exe : ch4_Stack.o TStoixeioyStoivas.o Hanoi.o
	gcc ch4_Stack.o TStoixeioyStoivas.o Hanoi.o -o Hanoi.exe
Hanoi.o : Hanoi.c
	gcc -c Hanoi.c
TStoixeioyStoivas.o:TStoixeioyStoivas.c 
	gcc -c TStoixeioyStoivas.c
ch4_Stack.o :ch4_Stack.c
	gcc -c ch4_Stack.c
